config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get 'search' => 'pages#search'
  get 'house' => 'pages#house'
  get 'new' => 'pages#new'
  get 'new2' => 'pages#new2'
  get 'register' => 'pages#register'
  get 'user' => 'pages#user'
  get 'content-page' => 'pages#content-page'
  get 'edit-user' => 'pages#edit-user'
  get 'landing-page' => 'pages#landing-page'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZukerFrontEnd</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=630424637093473";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<%= render ('partials/navbar') %>
<div class="wrapper">
	<%= yield %>
</div>
<%= render ('partials/footer') %>
</body>
</html>

app/views/pages/content-page.html.erb
<div class="content-page-header" style="background-image: url(<%= image_path('bg1.jpg') %>)">
  <div class="content-page-header-inner">
    <h4 class="content-page-header-title">幫助中心</h4>
    <p class="content-page-header-description">有任何問題讓我們來協助您</p>
  </div>
</div>

 <div class="container">
   <div class="row">
    <div class="col m4 l3 s12">
      <ul class="section table-of-contents">
        <li><a href="#introduction">房東義務</a></li>
        <li><a href="#structure">新手上路</a></li>
        <li><a href="#initialization">隱私權政策</a></li>
      </ul>
    </div>
    <div class="col s12 m8 l9">
      <div class="content-container">
        <h3>房東義務</h3>
        <p>我們建議房東認真考慮自己的責任。出租能帶來豐富的閱歷，但同時意味著需要承擔一定的義務。除了待客標準，以下這些方法能助您成為一個有責任心的房東。</p>
        <div class="content-container-block">
          <h4>安全</h4>
          <p><strong>緊急聯繫</strong></p>
          <p>註明當地緊急電話號碼和最近的醫院。提供您的明確緊急聯繫號碼和備用號碼，以方便房客諮詢。同時向房客明確說明，如果有疑問或問題，怎樣才能聯繫到您。</p>
        </div>
        <div class="content-container-block">
          <h4>鄰居</h4>
          <p>我該如何為我的鄰居著想？</p>

          <p>
          <strong>大廈規定：</strong><br><br>

          確保向房客傳達大廈公共區域的規定。您甚至可能要通知您的鄰居您將有房客入住，並提醒房客不要打擾您的鄰居（如不要隨意敲鄰居家的門或按門鈴讓鄰居開門）。<br><br>

          <strong>吸煙：</strong><br><br>

          如果您不允許吸煙，我們建議您張貼標誌提醒房客。如果您允許吸煙，請確保在特定地方擺放有煙灰缸。<br><br>

          <strong>泊車：</strong><br><br>

          將建築及周圍的停車規則轉述給房客。</p>


        </div>
        <h3>FAQ</h3>
        <div class="faq-block">
          <h5 class="faq-title">我在Airbnb上出租房屋需要通報誰？<i class="material-icons text-icon">add</i></h5>
          <p class="faq-answer">
            請檢查業主協會(HOA)或業主合作委員會(Co-op Board)的規定，確保裡面沒有禁止轉租或限制出租的條款。另外，請仔細閱讀您的租賃協議。如需要，請與您的房東確認。您還可以考慮在合同中添加附加條款，以消除各方的顧慮，並對各方的責任和義務進行規定。
          </p>
        </div>
        <div class="faq-block">
          <h5 class="faq-title">我在Airbnb上出租房屋需要通報誰？<i class="material-icons text-icon">add</i></h5>
          <p class="faq-answer">
            請檢查業主協會(HOA)或業主合作委員會(Co-op Board)的規定，確保裡面沒有禁止轉租或限制出租的條款。另外，請仔細閱讀您的租賃協議。如需要，請與您的房東確認。您還可以考慮在合同中添加附加條款，以消除各方的顧慮，並對各方的責任和義務進行規定。
          </p>
        </div>
        <div class="faq-block">
          <h5 class="faq-title">我在Airbnb上出租房屋需要通報誰？<i class="material-icons text-icon">add</i></h5>
          <p class="faq-answer">
            請檢查業主協會(HOA)或業主合作委員會(Co-op Board)的規定，確保裡面沒有禁止轉租或限制出租的條款。另外，請仔細閱讀您的租賃協議。如需要，請與您的房東確認。您還可以考慮在合同中添加附加條款，以消除各方的顧慮，並對各方的責任和義務進行規定。
          </p>
        </div>
      </div>
    </div>
  </div>
 </div>

app/views/pages/edit-user.html.erb
<div class="cover-photo"  style="background-image:url(<%= image_url('cover-photo.jpg') %>);">
</div>
<div class="profile-action-bar">
	<div class="container">
		<div class="profile-user-info">
			<span class="profile-user-avatar">
				<%= image_tag('avatar.jpg') %>
			</span>
			<h5 class="profile-user-name">劉政軒</h5>
		</div>
		<ul>
			<li><a href="#"><i class="material-icons text-icon">settings</i>編輯個人資料</a></li>
			<li><a href="#"><i class="material-icons text-icon">delete</i>刪除帳號</a></li>
		</ul>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col s12">
			<div class="profile-user">
				<div class="col s12">
					<div class="contact-info in-profile ">
						<form>
							<div class="col s12">
								<h4>編輯個人資料</h4>
							</div>
							<div class="col s12">
				        <div class="divider-text big-margin edit-user-divider" style="margin-top: 12px;">
				          <hr class="divider-text-left"/>基本資料<hr class="divider-text-right" />
				        </div>
							</div>
							<div class="col m6 s12">
								<p>姓氏</p>
								<input type="text" />
							</div>
							<div class="col m6 s12">
								<p>名字</p>
								<input type="text" />
							</div>
							<div class="col m6 s12">
								<p>電子郵件</p>
								<input type="text" />
							</div>
							<div class="col s12">
				        <div class="divider-text big-margin edit-user-divider">
				          <hr class="divider-text-left"/>聯絡電話<hr class="divider-text-right" />
				        </div>
							</div>
							<div class="col m6 s12">
								<p>手機 *</p>
								<input type="text" />
							</div>
							<div class="col m6 s12">
								<p>室內電話</p>
								<input type="text" />
							</div>
							<div class="col s12">
				        <div class="divider-text big-margin edit-user-divider">
				          <hr class="divider-text-left"/>通訊軟體<hr class="divider-text-right" />
				        </div>
							</div>
							<div class="col m6 s12">
								<p>LINE</p>
								<input type="text" />
							</div>
							<div class="col m6 s12">
								<p>WhatsApp</p>
								<input type="text" />
							</div>
							<div class="col s12">
				        <div class="divider-text big-margin edit-user-divider">
				          <hr class="divider-text-left"/>詳細資訊<hr class="divider-text-right" />
				        </div>
				        <textarea class="materialize-textarea"></textarea>
							</div>
							<div class="col s12">
								<div class="center-align" style="margin-top: 40px;">
									<button class="btn btn-large">儲存</button>
								</div>
							</div>
						</form>
						<div class="clear-both"></div>
					</div>
				</div>
				<div class="clear-both"></div>
			</div>
		</div>
	</div>
</div>

app/views/pages/index.html.erb
<header>
	<div class="container-fluid">
		<div class="header" style="background-image:url(<%= image_url('header-bg.jpg') %>);">
			<div class="header-inner">
				<h2 class="header-title">歡迎回家</h2>
				<p class="header-description">從超過190個國家的當地人租住獨一無二的家。</p>
				<a href="#" class="btn">如何使用租客</a>
			</div>
			<section class="action-bar" id="index-search">
				<div class="container-fluid">
					<div class="search-bar index">
						<div class="row">
							<div class="col m12 s12">
								<div class="action">
									<input class="" type="text" placeholder="搜尋學校.." />
								</div>
								<div class="action">
									<select class="browser-default">
									  <option value="1">不限房屋類型</option>
									  <option value="2">Option 2</option>
									  <option value="3">Option 3</option>
									</select>
								</div>
								<div class="action">
									<select class="browser-default">
									  <option value="1">不限期限</option>
									  <option value="2">Option 2</option>
									  <option value="3">Option 3</option>
									</select>
								</div>
								<div class="submit-btn">
									<a href="<%= search_path %>" class="btn">搜尋</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
		</div>
	</div>
</header>



<section id="index-school-list">
	<div class="container">
		<div class="row">
			<div class="col m4 s12">
				<div class="new-posts">
					<div class="new-post" style="background-image:url(<%= image_url('header-bg.jpg') %>);">
						<div class="new-post-avatar">
							<%= image_tag('avatar.jpg') %>
						</div>
						<p class="title">劉政軒 PO 的新房子</p>
						<p>萬隆 | 獨立套房</p>
					</div>
				</div>
			</div>
			<div class="col m8 s12">
				<div class="school-list-item nccu">
					<h4 class="school-name">
						政治大學
					</h4>
					<div class="school-info">

					</div>
				</div>
			</div>
			<div class="col m4 s12">
				<div class="school-list-item ntu">
					<h4 class="school-name">
						台灣大學
					</h4>
					<div class="school-info">

					</div>
				</div>
			</div>
			<div class="col m4 s12">
				<div class="school-list-item shu">
					<h4 class="school-name">
						世新大學
					</h4>
					<div class="school-info">

					</div>
				</div>
			</div>
			<div class="col m4 s12">
				<div class="school-list-item nteu">
					<h4 class="school-name">
						國北教大
					</h4>
					<div class="school-info">

					</div>
				</div>
			</div>
			<div class="col m4 s12">
				<div class="school-list-item ntust">
					<h4 class="school-name">
						台科大
					</h4>
					<div class="school-info">

					</div>
				</div>
			</div>
			<div class="col m4 s12">
				<div class="school-list-item ntnu">
					<h4 class="school-name">
						台師大
					</h4>
					<div class="school-info">

					</div>
				</div>
			</div>
			<div class="col m4 s12">
				<div class="school-list-item tmu">
					<h4 class="school-name">
						北醫大
					</h4>
					<div class="school-info">

					</div>
				</div>
			</div>
		</div>
	</div>
	<!--
	<div class="more-cta">
		<div class="more-cta-inner">
			<h5 class="white-text">喜歡我們的服務嗎？</h5>
			<a href="#" class="btn">立即註冊</a>
		</div>
	</div>
	-->
</section>

app/views/partials/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row margin-bottom-none">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-2">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="<%= content_page_path %>">房東須知</a></li>
          <li><a class="grey-text text-lighten-3" href="<%= content_page_path %>">新手上路</a></li>
          <li><a class="grey-text text-lighten-3" href="<%= content_page_path %>">關於我們</a></li>
          <li><a class="grey-text text-lighten-3" href="<%= content_page_path %>">隱私權條款</a></li>
        </ul>
      </div>
      <div class="col s12">
        <div class="footer-copyright">
          <span class="grey-text text-lighten-3">© 2014 Copyright Text</span>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/partials/_navbar.html.erb
<nav class="fixed-navbar">
  <div class="nav-wrapper container">
    <a href="<%= root_path %>" class="brand-logo"><%= image_tag('logo-h.png') %></a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><a href="#login" class="modal-trigger">登入/註冊</a></li>
      <li><a href="<%= new_path %>">立即刊登</a></li>
      <li><a href="<%= user_path %>"><span class="nav-avatar"><%= image_tag('avatar.jpg') %>劉政軒</span></a></li>
      <li><a href="#">English</a></li>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><a href="sass.html">Sass</a></li>
      <li><a href="badges.html">Components</a></li>
      <li><a href="collapsible.html">Javascript</a></li>
      <li><a href="mobile.html">Mobile</a></li>
    </ul>
  </div>
</nav>
<div id="login" class="modal login-popup">
  <div class="modal-content">
    <div class="top-bar">
      <a id="close-login-popup">
        <i class="material-icons">close</i>
      </a>
    </div>
    <div class="row">
      <div class="col s12" style="padding: 0;">
        <ul class="tabs">
          <li class="tab col s6"><a class="active" href="#tab-login">登入</a></li>
          <li class="tab col s6"><a href="#tab-register">註冊</a></li>
        </ul>
      </div>
      <div id="tab-login" class="col s12 tab-content">
        <a class="fb-login-btn">Facebook 登入</a>
        <div class="divider-text">
          <hr class="divider-text-left"/>OR<hr class="divider-text-right" />
        </div>
        <form class="col s12">
          <div class="row">
            <div class="input-field col s12">
              <p for="account">帳號</p>
              <input id="account" type="text">
            </div>
            <div class="input-field col s12">
              <p for="password">密碼</p>
              <input id="password" type="password">
            </div>
          </div>
          <div class="row">
            <p>
              <a href="#">忘記密碼</a>
            </p>
            <btn type="submit" class="btn">登入</btn>
            <p>
              還沒有帳號？
              <a href="#tab-go-register">註冊</a>
            </p>
          </div>
        </form>
      </div>
      <div id="tab-register" class="col s12 tab-content">
        <form class="col s12">
          <div class="row">
            <div class="input-field col s6">
              <p for="last_name">姓氏</p>
              <input id="last_name" type="text">
            </div>
            <div class="input-field col s6">
              <p for="first_name">名字</p>
              <input id="first_name" type="text">
            </div>
            <div class="input-field col s6">
              <p for="phone">手機</p>
              <input id="phone" type="text">
            </div>
            <div class="input-field col s6">
              <p for="email">email</p>
              <input id="email" type="email">
            </div>
            <div class="input-field col s6">
              <p for="password">密碼</p>
              <input id="password" type="password">
            </div>
            <div class="input-field col s6">
              <p for="password_confirm">確認密碼</p>
              <input id="password_confirm" type="password">
            </div>
          </div>
          <div class="row">
            <btn type="submit" class="btn">註冊</btn>
          </div>
        </form>

      </div>
    </div>

  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $(".button-collapse").sideNav();
    $('.modal-trigger').leanModal();

    $('a[href="#login"]').click(function(){
      $('ul.tabs').tabs('select_tab', 'tab-login');
    });

    $('a[href="#tab-go-register"]').click(function(){
      $('ul.tabs').tabs('select_tab', 'tab-register');
    });

    $('#close-login-popup').click(function(){
      $('#login').closeModal();
    });

    $('.faq-block').click(function(){
      $(this).toggleClass('active');
      $(this).children('.faq-answer').slideToggle(500);
    })
  });
</script>